package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	_ "github.com/nutchapon-m/go-pre-test-11/docs" // docs is generated by Swag CLI, you have to import it.
	productHttp "github.com/nutchapon-m/go-pre-test-11/internal/adapter/handler/http"
	"github.com/nutchapon-m/go-pre-test-11/internal/adapter/repository/postgres"
	"github.com/nutchapon-m/go-pre-test-11/internal/config"
	"github.com/nutchapon-m/go-pre-test-11/internal/service"
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title Go Pre-Test API
// @version 1.0
// @description This is a sample server for managing products.
// @host localhost:8080
// @BasePath /
func main() {
	// 1. Load Config
	cfg := config.Load()

	// 2. Setup Database
	connConfig, err := pgxpool.ParseConfig(cfg.DatabaseURL)
	if err != nil {
		log.Fatalf("Unable to parse config: %v\n", err)
	}
	dbPool, err := pgxpool.NewWithConfig(context.Background(), connConfig)
	if err != nil {
		log.Fatalf("Unable to connect to database: %v\n", err)
	}
	defer dbPool.Close()

	if err := dbPool.Ping(context.Background()); err != nil {
		log.Fatalf("Unable to ping database: %v\n", err)
	}
	log.Println("Connected to database")

	// 3. Setup Dependencies
	productRepo := postgres.NewProductRepository(dbPool)
	productService := service.NewProductService(productRepo)
	productHandler := productHttp.NewProductHandler(productService)

	// 4. Setup Echo
	e := echo.New()
	e.Use(middleware.RequestLogger())
	e.Use(middleware.Recover())
	// CORS? add if needed

	// 5. Routes
	e.POST("/product", productHandler.CreateProduct)
	e.PATCH("/product/:id", productHandler.PatchProduct)

	// Swagger setup
	e.GET("/swagger/*", echo.WrapHandler(httpSwagger.Handler()))

	// 6. Start Server
	go func() {
		if err := e.Start(":" + cfg.AppPort); err != nil && err != http.ErrServerClosed {
			e.Logger.Fatal("shutting down the server")
		}
	}()

	// 7. Graceful Shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, os.Interrupt)
	<-quit
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := e.Shutdown(ctx); err != nil {
		e.Logger.Fatal(err)
	}
}
